Part 3: Fum shutdown flow (#690)
* initial checkin

Signed-off-by: Chen Jing <jingch@vmware.com>

* update helm chart

Signed-off-by: Chen Jing <jingch@vmware.com>

* update helm chart

Signed-off-by: Chen Jing <jingch@vmware.com>

* update helm chart

Signed-off-by: Chen Jing <jingch@vmware.com>

* Change clusterrole to role

Signed-off-by: Chen Jing <jingch@vmware.com>

* address comment

Signed-off-by: Chen Jing <jingch@vmware.com>

* fix issues

Signed-off-by: Chen Jing <jingch@vmware.com>

diff --git a/helm-charts/UpgradeManager/templates/fate-mysql-upgrade-job.yaml b/helm-charts/UpgradeManager/templates/fate-mysql-upgrade-job.yaml
--- a/helm-charts/UpgradeManager/templates/fate-mysql-upgrade-job.yaml
+++ b/helm-charts/UpgradeManager/templates/fate-mysql-upgrade-job.yaml
@@ -1,17 +1,27 @@
 apiVersion: batch/v1
 kind: Job
-{{- with .Values }}
 metadata:
-  name: fate-mysql-upgrade-job-{{ .start }}-to-{{ .target }}
+  name: fate-mysql-upgrade-job
 spec:
-  backoffLimit: 1
+  backoffLimit: 0
   template:
     spec:
+      serviceAccountName: fum
       containers:
         - name: fate-mysql-upgrader
           image: federatedai/fate-upgrade-manager:latest
           imagePullPolicy: IfNotPresent
-          command: ["python", "upgrade-mysql.py", "{{ .username }}",
-                    "{{ .password }}", "{{ .start }}", "{{ .target }}"]
+          command:
+            - "/bin/bash"
+            - "-c"
+            - |
+              python shutdown-flow.py {{ .Release.Namespace }}
+              retVal=$?
+              if [ $retVal -ne 0 ]; then
+                echo "failed to terminate the flow's pod"
+              else
+                {{- with .Values }}
+                python upgrade-mysql.py {{ .username }} {{ .password }} {{ .start }} {{ .target }}
+                {{- end }}
+              fi
       restartPolicy: Never
-{{- end }}
