address comment
Signed-off-by: Chen Jing <jingch@vmware.com>

diff --git a/helm-charts/UpgradeManager/templates/fate-mysql-upgrade-job.yaml b/helm-charts/UpgradeManager/templates/fate-mysql-upgrade-job.yaml
--- a/helm-charts/UpgradeManager/templates/fate-mysql-upgrade-job.yaml
+++ b/helm-charts/UpgradeManager/templates/fate-mysql-upgrade-job.yaml
@@ -1,7 +1,7 @@
 apiVersion: batch/v1
 kind: Job
 metadata:
-  name: fate-mysql-upgrade-job-{{ .start }}-to-{{ .target }}
+  name: fate-mysql-upgrade-job
 spec:
   backoffLimit: 0
   template:
@@ -16,7 +16,12 @@ spec:
             - "-c"
             - |
               python shutdown-flow.py {{ .Release.Namespace }}
-              {{- with .Values }}
-              python upgrade-mysql.py {{ .username }} {{ .password }} {{ .start }} {{ .target }}w
-              {{- end }}
+              retVal = $?
+              if [ $retVal -ne 0 ]; then
+                echo "failed to terminate the flow's pod"
+              else
+                {{- with .Values }}
+                python upgrade-mysql.py {{ .username }} {{ .password }} {{ .start }} {{ .target }}w
+                {{- end }}
+              fi
       restartPolicy: Never
